# https://docs.travis-ci.com/user/languages/csharp/
# https://docs.travis-ci.com/user/docker/
sudo: required
# Not using the `csharp` language, since I've got my own docker image. Instead,
# using the _yet to be documented_ `bash` language. Follow the links from:
# https://github.com/travis-ci/travis-ci/issues/4895 for details.
language: bash

services:
  - docker

script:
  # TODO: move docker build to a `before_install:` step, when tests are
  # executed from an entrypoint.
  - docker build -t hello_world_app HelloWorld/.
